In [23]:
import pandas as pd
import numpy as np

df = pd.read_excel("/content/Lab Session Data.xlsx",sheet_name='Purchase data')


A_column= ['Candies (#)','Mangoes (Kg)','Milk Packets (#)']

A = df[A_column].values
print(A)

C_column= ['Payment (Rs)']

C = df[C_column].values
print(C)
dimension = A.shape[1]
print(f"THe dimension of the matrix is {dimension}")
# Shape returns the no. of rows or columns of a matrix
vector = A.shape[0]
print(f"THe no. of vectors in the matrix is {vector}")
rank = np.linalg.matrix_rank(A)
print(f"The rank of the matrix is {rank}")
pseudo_inverse = np.linalg.pinv(A)
print(f"The pseudo inverse of the matrix is {pseudo_inverse}")
X = np.dot(pseudo_inverse,C)
print(f"The cost of each element in the matrix is {X}")

[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
THe dimension of the matrix is 3
THe no. of vectors in the matrix is 10
The rank of the matrix is 3
The pseudo inverse of the matrix is [[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]
The cost of each element in the matrix is [[ 1.]
 [55.]
 [18.]]
